spring:
  cache:
    cache-names:
      - rate-limit-auth-strict
      - rate-limit-auth-tokens
      - rate-limit-user-writes
      - rate-limit-user-reads
      - rate-limit-refresh
      - rate-limit-product-reads
      - rate-limit-product-writes

    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  cache-to-use: redis-jedis
  filters:
    - id: auth-strict
      cache-name: rate-limit-auth-strict
      url: /api/v1/auth/(register|authenticate)
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 5
              time: 15
              unit: minutes

    - id: auth-tokens
      cache-name: rate-limit-auth-tokens
      url: /api/v1/auth/(logout|logout-all)
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 1
              unit: hours

    - id: auth-refresh
      cache-name: rate-limit-refresh
      url: /api/v1/auth/refresh
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 20
              time: 15
              unit: minutes

    - id: user-writes
      cache-name: rate-limit-user-writes
      url: /api/v1/user/me
      rate-limits:
        - execute-condition: "getMethod() == 'PATCH' or getMethod() == 'DELETE'"
          cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 20
              time: 1
              unit: hours

    - id: user-reads
      cache-name: rate-limit-user-reads
      url: /api/v1/user/me
      rate-limits:
        - execute-condition: "getMethod() == 'GET'"
          cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
    - id: product-reads
      cache-name: rate-limit-product-reads
      url: /api/v1/products.*
      rate-limits:
        - execute-condition: "getMethod() == 'GET'"
          cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 300
              time: 1
              unit: minutes

    - id: product-writes
      cache-name: rate-limit-product-writes
      url: /api/v1/products.*
      rate-limits:
        - execute-condition: "getMethod() == 'POST' or getMethod() == 'PATCH' or getMethod() == 'DELETE'"
          cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 60
              time: 1
              unit: hours